module Libzmq.Bindings
  ( -- * Functions

    -- ** Context
    zmq_ctx_new,
    zmq_ctx_term,
    zmq_ctx_shutdown,
    zmq_ctx_set,
    zmq_ctx_get,

    -- ** Message
    zmq_msg_init,
    zmq_msg_init_size,
    -- zmq_msg_init_data,
    zmq_msg_send,
    zmq_msg_send__unsafe,
    zmq_msg_recv,
    zmq_msg_recv__unsafe,
    zmq_msg_close,
    zmq_msg_move,
    zmq_msg_copy,
    zmq_msg_data,
    zmq_msg_size,
    zmq_msg_more,
    zmq_msg_get,
    zmq_msg_set,
    zmq_msg_gets,

    -- ** Socket
    zmq_socket,
    zmq_close,
    zmq_setsockopt,
    zmq_getsockopt,
    zmq_bind,
    zmq_connect,
    zmq_unbind,
    zmq_disconnect,
    zmq_send,
    zmq_send__unsafe,
    zmq_send_const,
    zmq_send_const__unsafe,
    zmq_recv,
    zmq_recv__unsafe,
    zmq_socket_monitor,

    -- * Types
    Zmq_msg_t,

    -- * Constants

    -- ** Errors
    eADDRINUSE,
    eADDRNOTAVAIL,
    eAFNOSUPPORT,
    eCONNABORTED,
    eCONNREFUSED,
    eCONNRESET,
    eFSM,
    eHOSTUNREACH,
    eINPROGRESS,
    eMSGSIZE,
    eMTHREAD,
    eNETDOWN,
    eNETRESET,
    eNETUNREACH,
    eNOBUFS,
    eNOCOMPATPROTO,
    eNOTCONN,
    eNOTSOCK,
    eNOTSUP,
    ePROTONOSUPPORT,
    eTERM,
    eTIMEDOUT,

    -- ** Context options
    zMQ_IO_THREADS,
    zMQ_MAX_MSGSZ,
    zMQ_MAX_SOCKETS,
    zMQ_MSG_T_SIZE,
    zMQ_SOCKET_LIMIT,
    zMQ_THREAD_AFFINITY_CPU_ADD,
    zMQ_THREAD_AFFINITY_CPU_REMOVE,
    zMQ_THREAD_NAME_PREFIX,
    zMQ_THREAD_PRIORITY,
    zMQ_THREAD_SCHED_POLICY,

    -- ** Default for new contexts
    zMQ_IO_THREADS_DFLT,
    zMQ_MAX_SOCKETS_DFLT,
    zMQ_THREAD_PRIORITY_DFLT,
    zMQ_THREAD_SCHED_POLICY_DFLT,

    -- ** Socket types
    zMQ_DEALER,
    zMQ_PAIR,
    zMQ_PUB,
    zMQ_PULL,
    zMQ_PUSH,
    zMQ_REP,
    zMQ_REQ,
    zMQ_ROUTER,
    zMQ_STREAM,
    zMQ_SUB,
    zMQ_XPUB,
    zMQ_XSUB,

    -- ** Socket options
    zMQ_AFFINITY,
    zMQ_BACKLOG,
    zMQ_BINDTODEVICE,
    zMQ_BLOCKY,
    zMQ_CONFLATE,
    zMQ_CONNECT_ROUTING_ID,
    zMQ_CONNECT_TIMEOUT,
    zMQ_CURVE_PUBLICKEY,
    zMQ_CURVE_SECRETKEY,
    zMQ_CURVE_SERVER,
    zMQ_CURVE_SERVERKEY,
    zMQ_EVENTS,
    zMQ_FD,
    zMQ_GSSAPI_PLAINTEXT,
    zMQ_GSSAPI_PRINCIPAL,
    zMQ_GSSAPI_PRINCIPAL_NAMETYPE,
    zMQ_GSSAPI_SERVER,
    zMQ_GSSAPI_SERVICE_PRINCIPAL,
    zMQ_GSSAPI_SERVICE_PRINCIPAL_NAMETYPE,
    zMQ_HANDSHAKE_IVL,
    zMQ_HEARTBEAT_IVL,
    zMQ_HEARTBEAT_TIMEOUT,
    zMQ_HEARTBEAT_TTL,
    zMQ_IMMEDIATE,
    zMQ_INVERT_MATCHING,
    zMQ_IPV6,
    zMQ_LAST_ENDPOINT,
    zMQ_LINGER,
    zMQ_MAXMSGSIZE,
    zMQ_MECHANISM,
    zMQ_MULTICAST_HOPS,
    zMQ_MULTICAST_MAXTPDU,
    zMQ_PLAIN_PASSWORD,
    zMQ_PLAIN_SERVER,
    zMQ_PLAIN_USERNAME,
    zMQ_PROBE_ROUTER,
    zMQ_RATE,
    zMQ_RCVBUF,
    zMQ_RCVHWM,
    zMQ_RCVMORE,
    zMQ_RCVTIMEO,
    zMQ_RECONNECT_IVL,
    zMQ_RECONNECT_IVL_MAX,
    zMQ_RECOVERY_IVL,
    zMQ_REQ_CORRELATE,
    zMQ_REQ_RELAXED,
    zMQ_ROUTER_HANDOVER,
    zMQ_ROUTER_MANDATORY,
    zMQ_ROUTER_RAW,
    zMQ_ROUTING_ID,
    zMQ_SNDBUF,
    zMQ_SNDHWM,
    zMQ_SNDTIMEO,
    zMQ_SOCKS_PROXY,
    zMQ_STREAM_NOTIFY,
    zMQ_SUBSCRIBE,
    zMQ_TCP_KEEPALIVE,
    zMQ_TCP_KEEPALIVE_CNT,
    zMQ_TCP_KEEPALIVE_IDLE,
    zMQ_TCP_KEEPALIVE_INTVL,
    zMQ_TCP_MAXRT,
    zMQ_THREAD_SAFE,
    zMQ_TOS,
    zMQ_TYPE,
    zMQ_UNSUBSCRIBE,
    zMQ_USE_FD,
    zMQ_VMCI_BUFFER_MAX_SIZE,
    zMQ_VMCI_BUFFER_MIN_SIZE,
    zMQ_VMCI_BUFFER_SIZE,
    zMQ_VMCI_CONNECT_TIMEOUT,
    zMQ_XPUB_MANUAL,
    zMQ_XPUB_NODROP,
    zMQ_XPUB_VERBOSE,
    zMQ_XPUB_VERBOSER,
    zMQ_XPUB_WELCOME_MSG,
    zMQ_ZAP_DOMAIN,

    -- ** Message options
    zMQ_MORE,
    zMQ_SHARED,

    -- ** Send/recv options
    zMQ_DONTWAIT,
    zMQ_SNDMORE,

    -- ** Security mechanisms
    zMQ_CURVE,
    zMQ_GSSAPI,
    zMQ_NULL,
    zMQ_PLAIN,

    -- ** RADIO-DISH protocol
    zMQ_GROUP_MAX_LENGTH,

    -- ** GSSAPI principal name types
    zMQ_GSSAPI_NT_HOSTBASED,
    zMQ_GSSAPI_NT_KRB5_PRINCIPAL,
    zMQ_GSSAPI_NT_USER_NAME,

    -- ** Socket transport events (TCP, IPC and TIPC only)
    zMQ_EVENT_ACCEPTED,
    zMQ_EVENT_ACCEPT_FAILED,
    zMQ_EVENT_ALL,
    zMQ_EVENT_BIND_FAILED,
    zMQ_EVENT_CLOSED,
    zMQ_EVENT_CLOSE_FAILED,
    zMQ_EVENT_CONNECTED,
    zMQ_EVENT_CONNECT_DELAYED,
    zMQ_EVENT_CONNECT_RETRIED,
    zMQ_EVENT_DISCONNECTED,
    zMQ_EVENT_HANDSHAKE_FAILED_AUTH,
    zMQ_EVENT_HANDSHAKE_FAILED_NO_DETAIL,
    zMQ_EVENT_HANDSHAKE_FAILED_PROTOCOL,
    zMQ_EVENT_HANDSHAKE_SUCCEEDED,
    zMQ_EVENT_LISTENING,
    zMQ_EVENT_MONITOR_STOPPED,

    -- ** Protocol errors
    zMQ_PROTOCOL_ERROR_WS_UNSPECIFIED,
    zMQ_PROTOCOL_ERROR_ZAP_BAD_REQUEST_ID,
    zMQ_PROTOCOL_ERROR_ZAP_BAD_VERSION,
    zMQ_PROTOCOL_ERROR_ZAP_INVALID_METADATA,
    zMQ_PROTOCOL_ERROR_ZAP_INVALID_STATUS_CODE,
    zMQ_PROTOCOL_ERROR_ZAP_MALFORMED_REPLY,
    zMQ_PROTOCOL_ERROR_ZAP_UNSPECIFIED,
    zMQ_PROTOCOL_ERROR_ZMTP_CRYPTOGRAPHIC,
    zMQ_PROTOCOL_ERROR_ZMTP_INVALID_METADATA,
    zMQ_PROTOCOL_ERROR_ZMTP_INVALID_SEQUENCE,
    zMQ_PROTOCOL_ERROR_ZMTP_KEY_EXCHANGE,
    zMQ_PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_ERROR,
    zMQ_PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_HELLO,
    zMQ_PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_INITIATE,
    zMQ_PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_MESSAGE,
    zMQ_PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_READY,
    zMQ_PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_UNSPECIFIED,
    zMQ_PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_WELCOME,
    zMQ_PROTOCOL_ERROR_ZMTP_MECHANISM_MISMATCH,
    zMQ_PROTOCOL_ERROR_ZMTP_UNEXPECTED_COMMAND,
    zMQ_PROTOCOL_ERROR_ZMTP_UNSPECIFIED,

    -- ** Probe library capabilities
    zMQ_HAS_CAPABILITIES,

    -- * Error
    module Libzmq.Bindings.Internal.Error,
  )
where

import Libzmq.Bindings.Internal.Constants
import Libzmq.Bindings.Internal.Error
import Libzmq.Bindings.Internal.Functions
import Libzmq.Bindings.Internal.Types
